apiVersion: apps/v1
kind: Deployment

metadata:
  name: assignment-nagp
  namespace: assignment

spec:
  replicas: 4

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  selector:
    matchLabels:
      app: assignment-nagp

  template:
    metadata:
      labels:
        app: assignment-nagp

    spec:
      containers:
        - name: assignment-app

          image: us-central1-docker.pkg.dev/devops-assignment-500215/assignment-nagp/assignment-app:v2

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_URL

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
#I want to specifically use rolling-update strategy for this yaml file. At a time
# I want to update 50% of the pods