CREATE TABLE products (
      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
      category character varying(255),
      description character varying(255),
      name character varying(255),
      price numeric(38,2) NOT NULL,
      quantity integer,
      CONSTRAINT products_pkey PRIMARY KEY (id)
    );

INSERT INTO products(category, description, name, price, quantity)
    VALUES
    ('Stationary','Apsara Pencil', 'Pencil', 20, 150),
    ('Stationary','Trimax Pen', 'Pen', 80, 100),
    ('Electronics','Hitachi Air Conditioner', 'AC', 50000, 10),
    ('Electronics','LG Washing Machine', 'Washing Machine', 20000, 20),
    ('Fashion','Levis Jeans For Men', 'Jeans', 2500, 10);